import Head from 'next/head'
import { Button } from '@mui/material'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <>
          <Button
            target="_blank"
            href="http://localhost:5000/api/auth/discord"
            className="blackButton"
          >
            SignIn
          </Button>
          <div></div>
          <Button
            target="_blank"
            // 環境に応じて"sample"を書き換えてください
            href="https://dimicom-server.herokuapp.com/api/auth/discord"
            className="blackButton"
          >
            SignIn(heroku)
          </Button>
          <div></div>
          <Button
            variant='text'
            href="http://localhost:5000/api/auth/signout"
            className="blackButton"
          >
            SignOut
          </Button>
          <div></div>
          <Button
            variant='text'
            // 環境に応じて"sample"を書き換えてください
            href="https://dimicom-server.herokuapp.com/api/auth/signout"
            className="blackButton"
          >
            SignOut(heroku)
          </Button>
          <div></div>
        </>
      </div>
    </>
  )
}
